spring:
  application:
    name: springcloud-netflix-eureka-feign

server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true